### PR TITLE
Locking vehicle repairs vehicle doors

### PR DESCRIPTION
**Pull request by DisHade**
`local doorstate = getVehicleDoorState(theVehicle,0)

			if doorstate == 2 or doorstate == 3 or doorstate == 4 then
				outputDebugString("false")
			else
				setVehicleDoorState(theVehicle,0,0)
			end

			local doorstate1 = getVehicleDoorState(theVehicle,1)

			if doorstate == 2 or doorstate1 == 3 or doorstate1 == 4 then
				outputDebugString("false")
			else
				setVehicleDoorState(theVehicle,1,0)
			end

			local doorstate2 = getVehicleDoorState(theVehicle,2)

			if doorstate2 == 2 or doorstate2 == 3 or doorstate2 == 4 then
				outputDebugString("false")
			else
				setVehicleDoorState(theVehicle,2,0)
			end

			local doorstate3 = getVehicleDoorState(theVehicle,3)

			if doorstate3 == 2 or doorstate3 == 3 or doorstate3 == 4 then
				outputDebugString("false")
			else
				setVehicleDoorState(theVehicle,3,0)
			end

			local doorstate4 = getVehicleDoorState(theVehicle,4)

			if doorstate4 == 2 or doorstate4 == 3 or doorstate4 == 4 then
				outputDebugString("false")
			else
				setVehicleDoorState(theVehicle,4,0)
			end

			local doorstate5 = getVehicleDoorState(theVehicle,5)

			if doorstate5 == 2 or doorstate5 == 3 or doorstate5 == 4 then
				outputDebugString("false")
			else
				setVehicleDoorState(theVehicle,5,0)
			end`

I know it is long but i am new and for me it works and tank you for your amazing work!Keep doing what you doin

### CODE REVIEW

**Comment by DisHade** [comment]
I don't think i put the right things at the create pull because i am new to github

**Comment by DisHade** [comment]
`-- /addupgrade - by Hade (29/06/19) [Trial Admin]
function addupgrade(thePlayer,commandName,id)
	if exports.global:isPlayerTrialAdmin(thePlayer) then
		if not (isPedInVehicle(thePlayer)) then
			outputChatBox("[ERROR] You must be in a vehicle", thePlayer, 255,0,0)
		else
			if not (id) then
				outputChatBox("SYNTAX: /" .. commandName .. " [Upgrade ID]", thePlayer, 75, 230, 10)
			else
				local upgradeID = tonumber(id)
				local upgradeVehicle = getPedOccupiedVehicle(thePlayer)
				local upgradesuccess = addVehicleUpgrade( upgradeVehicle, upgradeID )

				local upgradeVehicleID = getElementData(upgradeVehicle,"vehicle:id")
				local thePlayerName = exports.global:getStaffTitle(thePlayer)

				if (upgradesuccess) then
					outputChatBox( "[INFO] ".. getVehicleUpgradeSlotName ( id ) .. " upgrade was added.", thePlayer, 75, 230, 10)
					exports.global:sendMessageToAdmins("[INFO] " .. thePlayerName .. " has upgraded vehicle #" .. upgradeVehicleID .. " with ".. getVehicleUpgradeSlotName ( id ) .. " ("..upgradeID..").", 1)
					exports.logs:addLog(thePlayer, 2, thePlayerName, "has upgraded vehicle #"..upgradeVehicleID.. " with "..getVehicleUpgradeSlotName ( id ).." ("..upgradeID..").")
				else
					outputChatBox("[ERROR] Failed to upgrade", thePlayer, 255,0,0)
				end
			end
		end
	end
end
addCommandHandler("addupgrade",addupgrade)`

**Comment by DisHade** [comment]
addupgrade command complete with logs, i wanted to share it with you but i didn't know where to put it so i inserted it here

**Comment by unitt99** [comment]
Why are you not editing files, the whole point of Pull Requests are so you edit files and then make the request to merge them into the existing codebase. @DisHade

**Pull request closed without merging**
